# Site settings
title: "Techshaw Podcast"
description: > 
  Take a ride through a burmese tech scene by Burmese, for Burmese

author: Techshaw Cast
email: techshawcast@gmail.com
twitter_username: 
github_username: 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techshawcast.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

